package cdac.b1.utils;

import static java.time.LocalDate.parse;

import java.util.Map;

import cdac.b1.core.Contact;
import cdac.b1.exceptions.ContactBookException;
import cdac.b1.tester.PhoneBookTester;

public class ContactValidations {
	public static Contact inputValidation(String pNo, String name, 
			String dob, String email, Map<String, Contact>map) 
					throws ContactBookException {
			phoneNumberBelongsValidation(pNo, map);
			nameAndDobValidation(dob, name, map);
				return new Contact(pNo, name, parse(dob), email);
		
	}

	private static void nameAndDobValidation(String dob, String name, Map<String, Contact> map) 
			throws ContactBookException {
		for(Contact c : map.values()) {
			if(c.getName().equalsIgnoreCase(name) && c.getDob().equals(parse(dob))) {
				throw new ContactBookException(" Date and Name Already Exists!");
			}
		}
		
	}

	private static void phoneNumberBelongsValidation(String pNo, Map<String, Contact> map)
			throws ContactBookException {
		for(Contact c : map.values()) {
			if(c.getpNo().equals(pNo)) {
				throw new ContactBookException(pNo + " Already Exists!");
			}
		}
		
	}
}
